services:
  # Single Web Service (Python + Frontend)
  - type: web
    name: wotnot-app
    env: python
    plan: free
    buildCommand: |
      pip install -r backend/requirements.txt
      cd frontend/app && npm install && npm run build
    startCommand: |
      cd backend && python server.js
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: NODE_VERSION
        value: 18.18.0
